# Generated by Django 4.2.3 on 2023-12-13 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="Profile",
            new_name="profile",
        ),
    ]
